### ISSUE TITLE
Add .env

### ISSUE THREAD

**Issue by felipekian** [hermino/bombeiro-sos#3]
E ai blz?

Teria como add o arquivo modelo de .env que está sendo ignorado pelo git?

por exemplo *.env.exemplo* contendo as variáveis que estão sendo usadas.

Valeu.

Att, Felipe

**Comment by tallesbezerra** [comment]
Em dom., 29 de nov. de 2020 às 22:52, Felipe Derkian <
notifications@github.com> escreveu:
